# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: twig

before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/twig/main.go
    binary: twig
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

homebrew_casks:
  - repository:
      owner: 708u
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/708u/twig"
    description: "Simplify git worktree workflows with automatic branch creation, symlinks, and change syncing"
    completions:
      bash: completion/twig.bash
      zsh: completion/twig.zsh
      fish: completion/twig.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
          end

archives:
  - formats: [tar.gz]
    files:
      - LICENSE
      - README.md
      - completion/*
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  groups:
    - title: "Breaking Changes"
      regexp: '^.*!:.+$'
      order: 0
    - title: "New Features"
      regexp: '^feat(\(.+\))?:.+$'
      order: 1
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?:.+$'
      order: 2
    - title: "Performance"
      regexp: '^perf(\(.+\))?:.+$'
      order: 3
    - title: "Documentation"
      regexp: '^docs(\(.+\))?:.+$'
      order: 4
    - title: "Other Changes"
      order: 999
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"

release:
  name_template: "v{{.Version}}"
  footer: |
    ---

    **Full Changelog**: https://github.com/708u/twig/compare/{{.PreviousTag}}...{{.Tag}}
